# Generated by Django 5.1.2 on 2024-12-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_source_credit_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='persantage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='returned_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
