# Generated by Django 5.1.2 on 2024-12-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_credit_persantage_credit_returned_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='details',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='type',
            field=models.CharField(choices=[('loan_bank', 'Loan from Bank'), ('own_investment', 'Own Investment'), ('order_price', 'Demand item Price')], max_length=20),
        ),
    ]
