# Generated by Django 5.1.2 on 2024-12-02 08:28

import django.core.validators
import finance.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_credit_amount_alter_credit_persantage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=finance.models.PositiveDecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='persantage',
            field=finance.models.PositiveDecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='returned_amount',
            field=finance.models.PositiveDecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
    ]
