# Generated by Django 5.1.2 on 2024-12-02 08:31

import django.core.validators
import finance.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_credit_amount_alter_credit_persantage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=finance.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=finance.models.PositiveDecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='persantage',
            field=finance.models.PositiveDecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='returned_amount',
            field=finance.models.PositiveDecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='debit',
            name='amount',
            field=finance.models.PositiveDecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financesummary',
            name='monthly_profit',
            field=finance.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financesummary',
            name='total_credit',
            field=finance.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financesummary',
            name='total_debit',
            field=finance.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=finance.models.PositiveDecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=finance.models.PositiveDecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
    ]
