# Generated by Django 5.1.2 on 2024-12-15 11:52

import django.core.validators
import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_account_balance_alter_credit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=finance.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=finance.models.PositiveDecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='persantage',
            field=finance.models.PositiveDecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='returned_amount',
            field=finance.models.PositiveDecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='debit',
            name='amount',
            field=finance.models.PositiveDecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='debit',
            name='type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('office_cost', 'Office Management Cost'), ('factory_demand', 'Factory Demand Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='financesummary',
            name='monthly_profit',
            field=finance.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financesummary',
            name='total_credit',
            field=finance.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='financesummary',
            name='total_debit',
            field=finance.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=finance.models.PositiveDecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=finance.models.PositiveDecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(0)]),
        ),
    ]
