# Generated by Django 5.1.1 on 2024-10-05 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Department/Company Name')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=200, verbose_name='Shop Name')),
                ('shop_owner', models.CharField(max_length=200, verbose_name='Shop Owner')),
                ('shop_phone', models.CharField(max_length=15, verbose_name='Shop Phone')),
                ('shop_nid', models.CharField(max_length=20, verbose_name='Shop NID')),
                ('shop_email', models.EmailField(max_length=254, verbose_name='Shop Email')),
                ('shop_address', models.TextField(verbose_name='Shop Address')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('thana', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('product_code', models.CharField(max_length=100, verbose_name='Product Code')),
                ('product_dp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product DP')),
                ('product_tp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product TP')),
                ('product_mrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product MRP')),
                ('product_sku', models.CharField(max_length=100, verbose_name='Product SKU')),
                ('product_factor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Factor')),
                ('product_details', models.TextField(blank=True, null=True, verbose_name='Product Details')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.department', verbose_name='Dept/Company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shop', verbose_name='Shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.zone', verbose_name='Shop Zone'),
        ),
    ]
