# Generated by Django 5.1.1 on 2024-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Item Quantity'),
        ),
    ]
