# Generated by Django 5.1.2 on 2024-10-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_product_product_code_alter_product_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flat_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Flat Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='percentage_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Percentage Discount'),
        ),
    ]
