# Generated by Django 5.1.2 on 2024-10-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_product_flat_discount_product_percentage_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('orders', models.ManyToManyField(to='dashboard.order', verbose_name='Select Orders')),
            ],
        ),
    ]
