# Generated by Django 5.1.2 on 2024-10-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dealerproductneed_dealerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerproductneed',
            name='demand_quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Item Quantity'),
        ),
    ]
