# Generated by Django 5.1.2 on 2024-10-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flat_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='percentage_discount',
        ),
    ]
