# Generated by Django 5.1.2 on 2024-11-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_offer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Stock Unavailable', 'Stock Unavailable'), ('On the Way', 'On the Way')], default='Pending', max_length=20),
        ),
    ]
