# Generated by Django 5.1.2 on 2024-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_stock_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerproductneed',
            name='admin_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerproductneed',
            name='dealer_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerproductneed',
            name='hos_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dealerproductneed',
            name='rsm_flag',
            field=models.BooleanField(default=False),
        ),
    ]
