# Generated by Django 5.1.2 on 2024-11-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_dealerproductneed_admin_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='count_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Count Stock'),
        ),
        migrations.AlterField(
            model_name='dealerproductneed',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('ROS_Approve', 'ROS_Approve'), ('HOS_Approve', 'HOS_Approve'), ('Admin_Approve', 'Admin_Approve'), ('Delivered_by_factory', 'Delivered_by_factory'), ('Received', 'Received')], default='Pending', max_length=20),
        ),
    ]
