# Generated by Django 5.1.2 on 2024-12-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_leavebalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
