# Generated by Django 5.1.2 on 2024-10-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_product_product_code_alter_product_product_sku'),
        ('user', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, to='dashboard.product', verbose_name='Dealer Products'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zones',
            field=models.ManyToManyField(blank=True, to='dashboard.zone', verbose_name='Dealer Zones'),
        ),
    ]
