# Generated by Django 5.1.2 on 2024-11-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_products_profile_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_location',
            field=models.CharField(blank=True, choices=[('HO', 'Head Office'), ('FA', 'Factory')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
