# Generated by Django 5.1.2 on 2024-11-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_job_location_profile_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
