# Generated by Django 5.1.2 on 2024-11-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_location',
            field=models.CharField(blank=True, choices=[('HEAD_OFFICE', 'Head Office'), ('FACTORY', 'Factory')], max_length=20, null=True),
        ),
    ]
