# Generated by Django 5.1.2 on 2024-11-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_location',
            field=models.CharField(blank=True, choices=[('HEAD_OFFICE', 'Head Office'), ('FACTORY', 'Factory'), ('OTHERS', 'others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
